name: Slack Notification

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Set Variables
              run: echo "SHORT_GITHUB_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

            - name: Send custom JSON data to Slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                        "text": "${{github.repository}} actions result: ${{job.status}}",
                        "blocks": [
                          {
                            "type": "header",
                            "text": {
                              "type": "plain_text",
                              "text": "Actions Result : ${{job.status}}"
                            }
                          }
                        ],
                        "attachments": [
                          {
                            "color": "#36a64f",
                            "blocks": [
                              {
                                "type": "section",
                                "fields": [
                                  {
                                    "title": "Repository",
                                    "value": "${{github.repository}}"
                                  },
                                  {
                                    "title": "Author",
                                    "value": "${{github.actor}}"
                                  },
                                  {
                                    "title": "Commit",
                                    "value": "<${{github.event.head_commit.url}} | ${{env.SHORT_GITHUB_SHA}}>"
                                  },
                                  {
                                    "title": "Commit Message",
                                    "value": "${{github.event.head_commit.message}}"
                                  }
                                ],
                                "thumb_url": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
                              }
                            ]
                          }
                        ]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
