name: Slack Notification

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Send custom JSON data to Slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                        "text": "${{github.action_repository}} actions result: ${{github.action_status}}",
                        "blocks": [
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "Actions Result : ${{github.action_status}}"
                            }
                          }
                        ],
                        "attachments": [
                          {
                            "blocks": [
                              {
                                "type": "section",
                                "fields": [
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Repository:*\n${{github.action_repository}}"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Author:*\n${{github.actor}}"
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
