name: Slack Test

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v2

            - name: Test Failure
              run: exit 1

            - name: If Actions Failure
              if: ${{failure()}}
              run: echo "ACTIONS_STATUS=Failure" >> $GITHUB_ENV

            - name: If Actions Success
              if: ${{success()}}
              run: echo "ACTIONS_STATUS=Success" >> $GITHUB_ENV

            - name: Send Slack Message
              if: ${{always()}}
              uses: ./.github/actions/slack-notify
              with:
                  status: ${{env.ACTIONS_STATUS}}
                  slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
