name: Slack Notification

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Set Variables
              run: echo "SHORT_GITHUB_SHA=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

            - name: Send custom JSON data to Slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                        "text": "${{github.action_repository}} actions result: ${{job.status}}",
                        "blocks": [
                          {
                            "type": "header",
                            "text": {
                              "type": "plain_text",
                              "text": "Actions Result : ${{job.status}}"
                            }
                          }
                        ],
                        "attachments": [
                          {
                            "blocks": [
                              {
                                "type": "section",
                                "fields": [
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Repository:*\n${{github.action_repository}}"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Author:*\n${{github.actor}}"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Commit:*\n<${{github.event.head_commit.url}} | ${{github.env.SHORT_GITHUB_SHA}}>"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Commit Message:*\n${{github.event.head_commit.message}}"
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
